import Head from 'next/head';
import DisplayOneItem from '../src/DiscoSingle';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sophie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>NOTHING MORE TO SAY</h1>
        <img src="https://www.nme.com/wp-content/uploads/2020/07/GettyImages-1138239418.jpg"
          width="1000"
          height="635"
          alt="the harbringer of pop music"
        />


        <h1>About SOPHIE:</h1>
        <p>Sophie Xeon, known by their stage name SOPHIE, was a Scottish muscician and artist known for their unique sound and involvemnet in the innovation of "Bubblegum" pop and other experimental pop genres.</p>

        <p>
          <em>On January 30th, 2021, Sophie tragically fell to her death in Athens, Greece at the age of 34. She is remembered by a large scope of artists, as well as
            <a href="https://www.legacy.com/news/celebrity-deaths/sophie-1986-2021-grammy-nominated-musician-and-producer/" target="_blank">many who felt touched by their music</a>.
          </em>
        </p>
      </main>
      <DisplayOneItem album="oil" />
    </div>
  )
}
